project_id = "slwpupadtakrnaqzluqc"

[functions.send-password-reset]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.generate-pix]
verify_jwt = true

[functions.process-card-verification]
verify_jwt = true

[functions.pagarme-webhook]
verify_jwt = false

[functions.get-users]
verify_jwt = true

[functions.clear-all-data]
verify_jwt = true

[functions.validate-document-ocr]
verify_jwt = true

[functions.save-payment-settings]
verify_jwt = true

[functions.cancel-expired-pix]
verify_jwt = false
